import sys

sys.path.append('..')


import math
import re
from random import *
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pickle

from config import Config


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def init_weights(m):
    if isinstance(m, torch.nn.Linear):
        trunc_normal_(m.weight, std=0.02)
        if m.bias is not None:
            torch.nn.init.constant_(m.bias, 0)
    elif isinstance(m, torch.nn.LayerNorm):
        torch.nn.init.constant_(m.bias, 0)
        torch.nn.init.constant_(m.weight, 1.0)


class BaseBERT(nn.Module):
    def __init__(self, Config, input_dim, hidden_dim, num_layers=3, nheads=8,  maxlen: int = 201):
        super(BaseBERT, self).__init__()
        self.traj_embedding = nn.Linear(input_dim, Config.seq_embedding_dim)

        self.nheads = nheads

        self.pe = LearnablePositionalEncoding(Config.seq_embedding_dim, 0.1)

        self.max_length = maxlen

        structural_attn_layers = nn.TransformerEncoderLayer(Config.seq_embedding_dim, nheads, hidden_dim, 0.1)
        self.structural_attn = nn.TransformerEncoder(structural_attn_layers, num_layers)

        self.W = nn.Parameter(torch.randn(Config.seq_embedding_dim, Config.seq_embedding_dim))

        self.weights = nn.Parameter(torch.randn(8) / 8.)
        # Learnable bias for each node
        self.bias = nn.Parameter(torch.zeros(Config.seq_embedding_dim))
        torch.nn.init.normal_(self.bias, std=0.02)



    def forward(self, cell_emb, traj_o, src_padding_mask, adj):
        B, L, d = cell_emb.shape
        """
        query gcn
        """
        normalized_weights = F.softmax(self.weights, dim=0)
        normalized_weights = normalized_weights.view(1, 1, 8, 1)
        weighted_adj_cells = adj * normalized_weights
        weighted_mean = weighted_adj_cells.sum(dim=2)
        weighted_mean += self.bias
        n_emb = F.relu(weighted_mean)
        cell_emb = cell_emb + torch.matmul(n_emb, self.W)


        cell_emb = self.pe(cell_emb)
        cell_emb = self.structural_attn(cell_emb.permute(1, 0, 2), src_key_padding_mask=src_padding_mask)
        traj_emb = cell_emb
        mask = 1 - src_padding_mask.T.unsqueeze(-1).expand(traj_emb.shape).float()
        traj_emb = mask * traj_emb

        return traj_emb.permute(1,0,2)

    @staticmethod
    def get_padding_mask(padding_mask):
        """
        return padding mask of [batch, seq_len, seq_len],
        with a bool matrix of [seq_len, seq_len].
        """
        B = padding_mask.size(0)
        # cls_token_mask = torch.zeros((B, 1), device=padding_mask.device)
        # padding_mask = torch.cat((cls_token_mask, padding_mask), dim=1)
        L = padding_mask.size(1)
        padding_mask = padding_mask.unsqueeze(1)
        final_padding_mask = padding_mask.expand(B, L, L)

        return final_padding_mask.bool()

class LearnablePositionalEncoding(nn.Module):
    def __init__(self, emb_size: int, dropout: float, maxlen: int = 201):
        super(LearnablePositionalEncoding, self).__init__()
        # Instead of fixed position encoding, we use a learnable parameter
        self.pos_embedding = nn.Parameter(torch.zeros(maxlen, emb_size))
        # Initialize the positional encoding parameter
        nn.init.uniform_(self.pos_embedding, -0.1, 0.1)  # You can experiment with different initialization strategies

        self.dropout = nn.Dropout(dropout)

    def forward(self, token_embedding: torch.Tensor):
        # Assume token_embedding is of shape [batch_size, seq_len, emb_size]
        # We need to expand position encoding to match the batch size
        batch_size, seq_len, _ = token_embedding.size()
        # Expand the position embedding to the whole batch
        pos_embedding = self.pos_embedding[:seq_len, :].unsqueeze(0).repeat(batch_size, 1, 1)
        # Add the learnable position encoding to the input token embeddings
        return self.dropout(token_embedding + pos_embedding)
